import { setTimeout as sleep } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import type { FastifyInstance } from 'fastify';
import { runner } from 'node-pg-migrate';
import { Pool } from 'pg';
import { pino } from 'pino';
import { seed } from '@tally/db';
import { buildProviderSim } from '@tally/provider-sim';
import { buildReceiver, type ReceivedEvent, type ReceiverOptions } from '@tally/receiver';
import { buildApp } from '@tally/api/app';
import { enqueueJob } from '@tally/core';
import type { WorkerConfig } from '../src/config.js';
import { startWorker, type RunningWorker } from '../src/worker.js';

// Full webhook path: intent E2E -> outbox event -> signed delivery to the
// receiver; redelivery dedupe; failing endpoint -> growing backoff -> dead
// (DLQ); ops requeue -> delivered. Real Postgres, real HTTP receiver, the real
// worker loops in-process.

let container: StartedPostgreSqlContainer;
let pool: Pool;
let providerSim: FastifyInstance;
let api: FastifyInstance;
let receiver: FastifyInstance;
let receiverUrl: string;
let worker: RunningWorker;
// Secret is generated by POST /v1/webhook_endpoints, so the receiver learns it
// after registration (options object is read per-request).
const receiverOptions: ReceiverOptions = { secret: 'unset' };

// Test clocks (defaults in src/config.ts): backoff base 50ms instead of 1s,
// 5 attempts instead of 10, deterministic jitter (rand pinned to 0.5) so the
// retry ladder is exactly 75/150/300/600ms and monotonicity is assertable.
const MAX_ATTEMPTS = 5;
const testWorkerConfig = (databaseUrl: string): WorkerConfig => ({
  databaseUrl,
  providerUrl: 'http://127.0.0.1:9', // no completer traffic in this suite
  providerTimeoutMs: 1000,
  workerId: 'webhook-test-worker',
  logLevel: 'silent',
  batchSize: 5,
  pollMinMs: 20,
  pollMaxMs: 100,
  heartbeatMs: 250,
  visibilityMs: 5000,
  sweepIntervalMs: 1000,
  outboxIntervalMs: 50,
  outboxBatch: 50,
  completerIntervalMs: 600_000,
  completerGraceMs: 600_000,
  completerMaxAttempts: 25,
  idempotencyLockTimeoutMs: 90_000,
  livenessFile: '/tmp/tally-test-webhooks-alive',
  webhookTimeoutMs: 2000,
  maxAttempts: MAX_ATTEMPTS,
  backoffBaseMs: 50,
  backoffCapMs: 60_000,
  reconcileIntervalMs: 600_000, // this suite is about webhooks
  testJobs: false,
  rand: () => 0.5,
});

async function until<T>(
  what: string,
  deadlineMs: number,
  poll: () => Promise<T | null>,
): Promise<T> {
  const deadline = Date.now() + deadlineMs;
  for (;;) {
    const result = await poll();
    if (result !== null) return result;
    if (Date.now() > deadline) throw new Error(`timed out waiting for ${what}`);
    await sleep(10);
  }
}

async function receivedState(): Promise<{ events: ReceivedEvent[]; duplicates: number }> {
  const res = await fetch(`${receiverUrl}/received`);
  return (await res.json()) as { events: ReceivedEvent[]; duplicates: number };
}

async function setReceiverMode(failStatus: number | null): Promise<void> {
  const res = await fetch(`${receiverUrl}/mode`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ fail_status: failStatus }),
  });
  expect(res.status).toBe(200);
}

interface DeliveryDbRow {
  id: string;
  status: string;
  attempt: number;
  next_attempt_at: Date | null;
  last_response_code: number | null;
}

async function deliveryForEvent(eventId: string): Promise<DeliveryDbRow | null> {
  const result = await pool.query<DeliveryDbRow>(
    `SELECT id, status, attempt, next_attempt_at, last_response_code
     FROM webhook_deliveries WHERE event_id = $1`,
    [eventId],
  );
  return result.rows[0] ?? null;
}

beforeAll(async () => {
  container = await new PostgreSqlContainer('postgres:16-alpine').start();
  const databaseUrl = container.getConnectionUri();
  await runner({
    databaseUrl,
    dir: fileURLToPath(new URL('../../../packages/db/migrations', import.meta.url)),
    direction: 'up',
    migrationsTable: 'pgmigrations',
  });
  pool = new Pool({ connectionString: databaseUrl });
  const client = await pool.connect();
  try {
    await seed(client);
  } finally {
    client.release();
  }

  providerSim = buildProviderSim();
  const providerUrl = await providerSim.listen({ port: 0, host: '127.0.0.1' });

  receiver = buildReceiver(receiverOptions);
  receiverUrl = await receiver.listen({ port: 0, host: '127.0.0.1' });

  api = buildApp({
    config: {
      port: 0,
      databaseUrl,
      providerUrl,
      providerTimeoutMs: 1000,
      lockTimeoutMs: 90_000,
      logLevel: 'silent',
      enableProviderConfig: false,
    },
  });
  await api.ready();

  const registered = await api.inject({
    method: 'POST',
    url: '/v1/webhook_endpoints',
    payload: { url: `${receiverUrl}/webhooks` },
  });
  expect(registered.statusCode).toBe(201);
  const endpoint = registered.json<{ id: string; secret: string }>();
  expect(endpoint.secret).toMatch(/^whsec_[0-9a-f]{48}$/);
  receiverOptions.secret = endpoint.secret;

  worker = startWorker(testWorkerConfig(databaseUrl), pino({ level: 'silent' }));
});

afterAll(async () => {
  await worker?.stop();
  await api?.close();
  await receiver?.close();
  await providerSim?.close();
  await pool?.end();
  await container?.stop();
});

describe('intent E2E -> signed webhook delivery', () => {
  it('delivers both outbox events to the receiver with valid signatures', async () => {
    const res = await api.inject({
      method: 'POST',
      url: '/v1/payment_intents',
      headers: { 'idempotency-key': 'wh-1', 'content-type': 'application/json' },
      payload: { amount_minor: 10_000, currency: 'USD' },
    });
    expect(res.statusCode).toBe(200);
    expect(res.json<{ status: string }>().status).toBe('succeeded');

    // created + succeeded, fanned out from the outbox, signed, verified and
    // recorded by the receiver.
    const state = await until('both events at the receiver', 10_000, async () => {
      const s = await receivedState();
      return s.events.length >= 2 ? s : null;
    });
    expect(state.events.map((e) => e.type).sort()).toEqual([
      'payment_intent.created',
      'payment_intent.succeeded',
    ]);
    expect(state.duplicates).toBe(0);

    // Wait for the DB rows too: the worker commits the 'delivered' mark AFTER
    // the receiver's 200 response, so racing straight from the receiver state
    // to this assertion can observe a still-pending row.
    const deliveries = await until('both deliveries marked delivered', 10_000, async () => {
      const result = await pool.query<DeliveryDbRow>(
        `SELECT id, status, attempt, next_attempt_at, last_response_code FROM webhook_deliveries`,
      );
      return result.rows.length === 2 && result.rows.every((d) => d.status === 'delivered')
        ? result.rows
        : null;
    });
    for (const d of deliveries) {
      expect(d).toMatchObject({ status: 'delivered', attempt: 1, last_response_code: 200 });
    }

    // Every event dispatched exactly once, every delivery job done.
    const jobs = await pool.query<{ status: string }>(
      `SELECT status FROM jobs WHERE kind = 'deliver_webhook'`,
    );
    expect(jobs.rows.map((j) => j.status)).toEqual(['done', 'done']);
  });

  it('receiver dedupes a redelivery of the same event', async () => {
    const before = await receivedState();
    const delivered = await pool.query<{ id: string }>(
      `SELECT id FROM webhook_deliveries WHERE status = 'delivered' LIMIT 1`,
    );
    const deliveryId = delivered.rows[0]?.id ?? '';

    // Simulate an at-least-once redelivery: re-open the delivery and enqueue a
    // fresh job for it.
    await pool.query(`UPDATE webhook_deliveries SET status = 'pending' WHERE id = $1`, [
      deliveryId,
    ]);
    await enqueueJob(pool, 'deliver_webhook', { delivery_id: deliveryId });

    await until('redelivery to complete', 10_000, async () => {
      const row = await pool.query<{ status: string }>(
        `SELECT status FROM webhook_deliveries WHERE id = $1`,
        [deliveryId],
      );
      return row.rows[0]?.status === 'delivered' ? true : null;
    });

    const after = await receivedState();
    expect(after.events.length).toBe(before.events.length); // no double-processing
    expect(after.duplicates).toBe(before.duplicates + 1); // the dupe was seen and dropped
  });
});

describe('failing endpoint -> backoff -> DLQ -> requeue', () => {
  let eventId: string;
  let deliveryId: string;

  it('retries with monotonically growing next_attempt_at, then dead-letters at the cap', async () => {
    await setReceiverMode(500);
    const inserted = await pool.query<{ id: string }>(
      `INSERT INTO events (type, payload) VALUES ('test.fail', '{"n": 1}') RETURNING id`,
    );
    eventId = inserted.rows[0]?.id ?? '';

    // Track each attempt's scheduled retry time as it lands on the row.
    const nextAttemptAt = new Map<number, number>();
    const dead = await until('delivery to dead-letter', 30_000, async () => {
      const row = await deliveryForEvent(eventId);
      if (row === null) return null;
      if (row.next_attempt_at !== null)
        nextAttemptAt.set(row.attempt, row.next_attempt_at.getTime());
      return row.status === 'dead' ? row : null;
    });
    deliveryId = dead.id;
    expect(dead.attempt).toBe(MAX_ATTEMPTS);
    expect(dead.last_response_code).toBe(500);
    expect(dead.next_attempt_at).toBeNull();

    // Backoff grows: with jitter pinned at 0.5 the delays are 75/150/300/600ms,
    // so successive next_attempt_at values are strictly increasing AND their
    // gaps widen (each gap ~ the next doubled delay + pickup latency).
    const times = [...nextAttemptAt.entries()].sort(([a], [b]) => a - b).map(([, t]) => t);
    expect(times.length).toBe(MAX_ATTEMPTS - 1); // every non-final attempt scheduled a retry
    const gaps: number[] = [];
    for (let i = 1; i < times.length; i++) {
      const gap = (times[i] ?? 0) - (times[i - 1] ?? 0);
      expect(gap).toBeGreaterThan(0);
      gaps.push(gap);
    }
    for (let i = 1; i < gaps.length; i++) {
      expect(gaps[i] ?? 0).toBeGreaterThan(gaps[i - 1] ?? 0);
    }

    // The delivery job is dead too — nothing will retry it until an operator acts.
    const job = await pool.query<{ status: string; attempts: number }>(
      `SELECT status, attempts FROM jobs
       WHERE kind = 'deliver_webhook' AND payload ->> 'delivery_id' = $1`,
      [deliveryId],
    );
    expect(job.rows[0]).toMatchObject({ status: 'dead', attempts: MAX_ATTEMPTS });
  });

  it('shows up in the DLQ list and GET /v1/events/:id returns the event', async () => {
    const dlq = await api.inject({ method: 'GET', url: '/v1/deliveries?status=dead' });
    expect(dlq.statusCode).toBe(200);
    const { deliveries } = dlq.json<{
      deliveries: { id: string; event_type: string; attempt: number }[];
    }>();
    expect(deliveries).toHaveLength(1);
    expect(deliveries[0]).toMatchObject({
      id: deliveryId,
      event_type: 'test.fail',
      attempt: MAX_ATTEMPTS,
    });

    const event = await api.inject({ method: 'GET', url: `/v1/events/${eventId}` });
    expect(event.statusCode).toBe(200);
    expect(event.json<{ type: string }>().type).toBe('test.fail');
  });

  it('requeue resets the delivery and delivers once the endpoint recovers', async () => {
    await setReceiverMode(null);
    const requeued = await api.inject({
      method: 'POST',
      url: `/v1/deliveries/${deliveryId}/requeue`,
    });
    expect(requeued.statusCode).toBe(200);

    const row = await until('requeued delivery to succeed', 10_000, async () => {
      const d = await deliveryForEvent(eventId);
      return d?.status === 'delivered' ? d : null;
    });
    expect(row).toMatchObject({ attempt: 1, last_response_code: 200 }); // fresh attempt counter

    const state = await receivedState();
    expect(state.events.some((e) => e.id === eventId && e.type === 'test.fail')).toBe(true);

    // Requeueing a non-dead delivery is refused.
    const again = await api.inject({ method: 'POST', url: `/v1/deliveries/${deliveryId}/requeue` });
    expect(again.statusCode).toBe(409);
  });
});
