-- Up Migration

-- Tally core schema (project brief §4.1).
-- Money is ALWAYS bigint minor units (cents). Never floats: binary floating
-- point cannot represent decimal money exactly and drifts under summation.

-- Not in the brief's table list, but merchant_id is referenced by three tables
-- below; foreign keys need a target.
CREATE TABLE merchants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Chart of accounts. Balances are NEVER stored here — they are derived from
-- ledger_entries (see the balances view below).
CREATE TABLE accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL CHECK (
    type IN ('customer_receivable', 'provider_clearing', 'merchant_payable', 'platform_revenue')
  ),
  currency text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE payment_intents (
  id text PRIMARY KEY, -- ULID, generated by the intents service
  merchant_id uuid NOT NULL REFERENCES merchants (id),
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL,
  status text NOT NULL DEFAULT 'created' CHECK (
    status IN ('created', 'processing', 'requires_retry', 'succeeded', 'failed')
  ),
  provider_ref text,
  failure_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE idempotency_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id uuid NOT NULL REFERENCES merchants (id),
  key text NOT NULL,
  request_hash text NOT NULL,
  recovery_point text NOT NULL DEFAULT 'started' CHECK (
    recovery_point IN ('started', 'intent_created', 'provider_charged', 'ledger_posted', 'finished')
  ),
  locked_at timestamptz,
  response_code integer,
  response_body jsonb,
  intent_id text REFERENCES payment_intents (id),
  UNIQUE (merchant_id, key)
);

CREATE TABLE ledger_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intent_id text NOT NULL REFERENCES payment_intents (id),
  kind text NOT NULL CHECK (kind IN ('charge', 'fee', 'refund', 'reversal')),
  posted_at timestamptz NOT NULL DEFAULT now()
);

-- Idempotent posting: at most one ledger transaction per (intent, kind).
-- postTransaction's ON CONFLICT no-op path relies on this index.
CREATE UNIQUE INDEX ledger_transactions_intent_id_kind_idx
  ON ledger_transactions (intent_id, kind);

CREATE TABLE ledger_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id uuid NOT NULL REFERENCES ledger_transactions (id),
  account_id uuid NOT NULL REFERENCES accounts (id),
  direction text NOT NULL CHECK (direction IN ('debit', 'credit')),
  amount_minor bigint NOT NULL CHECK (amount_minor > 0)
);

CREATE INDEX ledger_entries_transaction_id_idx ON ledger_entries (transaction_id);
CREATE INDEX ledger_entries_account_id_idx ON ledger_entries (account_id); -- balances view groups by account

-- The ledger is APPEND-ONLY, enforced in the database and not just app code.
-- If ledger rows could be UPDATEd or DELETEd, a bug or an operator could
-- silently rewrite financial history, and derived balances/reconciliation
-- would prove nothing. Corrections are new compensating transactions
-- (kind 'refund' / 'reversal'), never edits. Triggers RAISE on any attempt.
CREATE FUNCTION raise_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% is append-only: corrections must be posted as new compensating transactions',
    TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER ledger_transactions_append_only
  BEFORE UPDATE OR DELETE ON ledger_transactions
  FOR EACH ROW EXECUTE FUNCTION raise_append_only();

CREATE TRIGGER ledger_entries_append_only
  BEFORE UPDATE OR DELETE ON ledger_entries
  FOR EACH ROW EXECUTE FUNCTION raise_append_only();

-- Balances are COMPUTED, never stored: the entries are the truth and a stored
-- balance is a cache that can drift (TigerBeetle-style reasoning).
-- Sign convention: credit-normal — balance_minor = SUM(credits) - SUM(debits),
-- uniform for every account. Liability-style accounts (merchant_payable,
-- platform_revenue) therefore read positive, asset-style accounts
-- (customer_receivable) read negative, and the whole ledger sums to exactly 0.
-- packages/core reduceBalances() implements the same convention in TS.
CREATE VIEW balances AS
SELECT
  a.id AS account_id,
  a.type,
  a.currency,
  COALESCE(
    SUM(CASE e.direction WHEN 'credit' THEN e.amount_minor ELSE -e.amount_minor END),
    0
  )::bigint AS balance_minor
FROM accounts a
LEFT JOIN ledger_entries e ON e.account_id = a.id
GROUP BY a.id;

-- Transactional outbox: events are written in the same TX as the state change
-- they describe, and drained by the worker.
CREATE TABLE events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_endpoints (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id uuid NOT NULL REFERENCES merchants (id),
  url text NOT NULL,
  secret text NOT NULL
);

CREATE TABLE webhook_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES events (id),
  endpoint_id uuid NOT NULL REFERENCES webhook_endpoints (id),
  attempt integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered', 'dead')),
  next_attempt_at timestamptz,
  last_response_code integer
);

CREATE INDEX webhook_deliveries_due_idx ON webhook_deliveries (status, next_attempt_at);

-- Hand-rolled job queue; the worker phase claims with FOR UPDATE SKIP LOCKED.
CREATE TABLE jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL,
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'done', 'failed')),
  run_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0,
  locked_at timestamptz,
  locked_by text
);

CREATE INDEX jobs_claim_idx ON jobs (status, run_at);
